version: "2"

services:
  app:
    image: "app-image:latest"
    build:
      context: .
    ports:
    - "8090:8090"
    container_name: app-compose
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://192.168.99.100:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: "db-image:latest"
    build:
      context: ./postgres
    ports:
      - "5432:5432"
    container_name: db-compose
    restart: always


